#!/bin/bash
VOL=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}')
VOLUMELEVEL=${VOL%?}
if [ $VOLUMELEVEL = 0 ];
then
   VOLUMEICON=""
elif [ $VOLUMELEVEL -gt 0 ] && [ $VOLUMELEVEL -lt 80 ];
then
   VOLUMEICON=""
elif [ $VOLUMELEVEL -ge 80 ];
then
   VOLUMEICON=""
fi
echo $VOLUMEICON $VOLUMELEVEL 𛰇
# ⟮⟯ 🕨 🕩  🕪 
